#! /bin/bash

set -x
set -euo pipefail

versionNumber="$1"
shift

trunk="$1"
shift

if ! ${__GIT_STATUS:-false}; then
    status=$(git status --short)
    if [ -n "$status" ]; then
        echo '(Modified)'
        exit
    fi
fi

commits=${__GIT_COMMITS:-$(git rev-list --count HEAD)}
commitsInBranch=${__GIT_COMMITS_IN_BRANCH:-$(git rev-list --count "$trunk"..HEAD)}
commitsInTrunk=$((commits - commitsInBranch))

bundleVersion="$versionNumber.$commitsInTrunk.$commitsInBranch"

echo "$bundleVersion"
