#! /bin/bash

trunk="$1"; shift
pr="$1"; shift

commitsFromRoot=$(git rev-list --count HEAD)

if [ "$pr" != "null" ]; then
    commitsInBranch=$(git rev-list --count "$trunk"..HEAD)
    commitsInTrunk=$((commitsFromRoot - commitsInBranch))
    bundleVersion="$commitsInTrunk.$pr.$commitsInBranch"
else
    bundleVersion="$commitsFromRoot"
fi

echo "$bundleVersion"
