#! /bin/bash

set -x
set -euo pipefail

appName="$1"
shift
formulaName="$1"
shift
provisioningDir="$1"
shift
casksDir="$1"
shift

lastRun=$(Publishing/LastRun)

gh run watch "$lastRun" --exit-status

Publishing/DownloadAndPublish "$lastRun" "$provisioningDir" "$casksDir" "$appName" "$formulaName"

(cd "$casksDir" && git add "$formulaName.rb" && git commit -m "Updated $appName." "$formulaName.rb" && git push)

/opt/homebrew/bin/brew update && /opt/homebrew/bin/brew reinstall grigorye/tools/"$formulaName"
