#! /bin/bash

set -x
set -euo pipefail

repoName="ReusableWorkflows"
submodule="ReusableWorkflows"

submoduleTag="$(git -C "$submodule" tag --points-at HEAD)"
submoduleShaOrTag="${submoduleTag:-$(git -C "$submodule" rev-parse HEAD)}"

for workflow in .github/workflows/*.yml; do
    sed -i '' -e "s|\(uses: .*/$repoName/\.github/workflows/.*\.yml@\).*|\1$submoduleShaOrTag|" "$workflow"
done
