#! /bin/bash

set -x
set -euo pipefail

xcodeproj="$1"
shift

scheme="$1"
shift

. "$(dirname "$0")"/Xcodebuild-env.sh

# It's important to delete Package.resolved before resolving dependencies,
# otherwise Xcode will not update dependencies.
find "$xcodeproj" -name Package.resolved -delete

# It's also important to have derived data path different from the one used,
# otherwise Xcode will not update dependencies either, as
# DerivedData/Project-Name/SourcePackages will be reused.
derivedDataPath=$(mktemp -d /tmp/"$(basename "$0")".XXXXXX)

argsToIgnoreDerivedData=(
    -derivedDataPath "$derivedDataPath"
    -scheme "$scheme" # "The flag -scheme, -testProductsPath, or -xctestrun is required when specifying -derivedDataPath".
)
xcodebuild "${argsToIgnoreDerivedData[@]}" -resolvePackageDependencies -project "$xcodeproj"
