#! /bin/bash

set -x
set -euo pipefail

repoName="ReusableWorkflows"

lastTag="$(git tag --points-at HEAD)"
lastTagOrSha="${lastTag:-$(git rev-parse HEAD)}"

for workflow in .github/workflows/*.yml; do
    sed -i '' -e "s|\(uses: .*/$repoName/\.github/workflows/.*\.yml@\).*|\1$lastTagOrSha|" "$workflow"
done
