on:
  workflow_call:
    inputs:
      build-configs:
        type: string
        required: true
      macos-app-scheme:
        type: string
        required: false
      ios-app-scheme:
        type: string
        required: false

jobs:
  increasing-number:
    name: 'Increasing number'
    uses: grigorye/ReusableWorkflows/.github/workflows/increasing-number-reusable.yml@e3a87cac31f5e6957c1dd19cca7923948d8d7d51

  build:
    name: 'Generic'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-given-app-configs.yml@e3a87cac31f5e6957c1dd19cca7923948d8d7d51
    needs: increasing-number
    with:
      increasing-number: ${{ needs.increasing-number.outputs.number }}
      build-configs: ${{ inputs.build-configs }}
      macos-app-scheme: ${{ inputs.macos-app-scheme }}
      ios-app-scheme: ${{ inputs.ios-app-scheme }}
    secrets: inherit
