name: "."

on:
  workflow_call:
    outputs:
      bundle_version:
        description: "16088707.63.0"
        value: ${{ jobs.main.outputs.bundle_version }}
      product_version:
        description: "0.1-16088707.63.0"
        value: ${{ jobs.main.outputs.product_version }}
      marketing_version:
        description: "0.1"
        value: ${{ jobs.main.outputs.marketing_version }}

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}

jobs:
  bump:
    uses: grigorye/ReusableWorkflows/.github/workflows/increasing-number-reusable.yml@v16

  main:
    name: "Generate versions"
    outputs:
      product_version: ${{ steps.compute.outputs.product_version }}
      marketing_version: ${{ steps.compute.outputs.marketing_version }}
      bundle_version: ${{ steps.compute.outputs.bundle_version }}
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: "Compute"
        id: compute
        run: |
          increasingNumber=${{ needs.bump.outputs.number }}

          BUNDLE_VERSION="${BUNDLE_VERSION:-$(GHAScripts/BundleVersion "$increasingNumber")}"
          marketingPatchVersion="${MARKETING_PATCH_VERSION:-$(GHAScripts/MarketingPatchVersion)}"
          marketingMajorMinorVersion="${MARKETING_MAJOR_MINOR_VERSION:-$(GHAScripts/MarketingMajorMinorVersion)}"
          MARKETING_VERSION="${MARKETING_VERSION:-$marketingMajorMinorVersion${marketingPatchVersion:+.$marketingPatchVersion}}"
          PRODUCT_VERSION="$MARKETING_VERSION-$BUNDLE_VERSION"

          echo "bundle_version=$BUNDLE_VERSION" >> $GITHUB_OUTPUT
          echo "marketing_version=$MARKETING_VERSION" >> $GITHUB_OUTPUT
          echo "product_version=$PRODUCT_VERSION" >> $GITHUB_OUTPUT
