name: macOS

on:
  workflow_call:
    inputs:
      bundle_version:
        type: string
        required: true

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}

jobs:
  release:
    runs-on: macos-12
    steps:
      - name: Prepare Environment
        run: |
          __BUNDLE_VERSION=${{ inputs.bundle_version }}
          echo "__BUNDLE_VERSION=$__BUNDLE_VERSION" >> $GITHUB_ENV
      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: "Swift Build"
        run: |
          swift build -c release

  test:
    runs-on: macos-12
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: latest-stable
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: "Swift Test"
        run: |
          swift test
