name: Linux

on:
  workflow_call:
    inputs:
      bundle_version:
        type: string
        required: true

env:
  __SWIFT_VERSION: 5.8

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}

jobs:
  env:
    name: "Prepare (Linux)"
    runs-on: ubuntu-latest
    outputs:
      __SWIFT_VERSION: ${{ steps.gen.outputs.__SWIFT_VERSION }}
    steps:
      - run: |
          echo '${{ toJSON(env) }}' > env.json
      - id: jq
        uses: sergeysova/jq-action@v2
        with:
          multiline: true
          cmd: |
            jq -r 'to_entries | .[] | .key + "=" + (.value | @sh)' env.json
      - name: "Convert environment variables to output"
        id: gen
        run: |
          echo '${{ steps.jq.outputs.value }}' | sed 's/%0A/\n/g' >> $GITHUB_OUTPUT

  release:
    name: "Build (Linux)"
    runs-on: ubuntu-latest
    needs: env
    container:
      image: swift:${{ needs.env.outputs.__SWIFT_VERSION }}-focal
    steps:
      - name: "Prepare Environment"
        run: |
          __BUNDLE_VERSION=${{ inputs.bundle_version }}
          echo "__BUNDLE_VERSION=$__BUNDLE_VERSION" >> $GITHUB_ENV
      - if: ${{ env.ACT }}
        name: "Hack container for local development"
        run: |
          apt-get update
          apt-get install -y nodejs zstd
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          swift package dump-package > package-dump.json
      - id: product-name
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            jq -r '.products[0].name' package-dump.json
      - name: "Introspect Swift Package"
        run: |
          __PRODUCT_NAME=${{ steps.product-name.outputs.value }}
          echo "__PRODUCT_NAME=$__PRODUCT_NAME" >> $GITHUB_ENV
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: .build
          key: ${{ runner.os }}-swift-${{ env.__SWIFT_VERSION }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: "Swift Build"
        run: |
          swift build -c release -Xswiftc -static-stdlib -Xlinker -lCoreFoundation -Xlinker -lCFURLSessionInterface
      - run: |
          chmod -R go+rx .build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.__PRODUCT_NAME }}
          # `release` is a symlink, apply glob as a workaround for https://github.com/actions/upload-artifact/issues/92
          path: |
            .build/release*/${{ env.__PRODUCT_NAME }}
            !.build/release?*

  test:
    name: "Test (Linux)"
    runs-on: ubuntu-latest
    needs: env
    container:
      image: swift:${{ needs.env.outputs.__SWIFT_VERSION }}-focal
    steps:
      - name: "Prepare Environment"
        run: |
          __BUNDLE_VERSION=${{ inputs.bundle_version }}
          echo "__BUNDLE_VERSION=$__BUNDLE_VERSION" >> $GITHUB_ENV
      - if: ${{ env.ACT }}
        name: "Hack container for local development"
        run: |
          apt-get update
          apt-get install -y nodejs zstd
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/cache@v3
        if: ${{ !env.ACT }}
        with:
          path: .build
          key: ${{ runner.os }}-swift-${{ env.__SWIFT_VERSION }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - run: |
          swift test --enable-test-discovery
      - run: |
          chmod -R go+rx .build
